name: 'Copy AWS Glue scripts to S3'

on:
  workflow_dispatch:
    inputs:
      environment:
        type: environment

permissions:
  id-token: write
  contents: read
  
jobs:
  upload_to_s3:
    name: 'Upload Glue scripts'
    runs-on: ubuntu-latest
    environment: ${{inputs.environment}}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{secrets.AWS_ACCOUNT_ID}}:role/${{vars.PROJECT_NAME}}-${{startsWith(inputs.environment, 'prod') && 'main' || 'bio'}}-${{inputs.environment}}-my-github-actions-${{startsWith(inputs.environment, 'prod') && 'push-glue' || 'copy-glue'}}
          aws-region: ${{vars.AWS_REGION}}
          mask-aws-account-id: true
      - run: |
          cd ./cfn/glue-jobs/
          zip -r9 ETL_tools.zip biosql_gene_views.py variant_annotation_categorization.py phenotypic_data_views.py call_lineages.py
          aws s3 cp ./  s3://${{secrets.GLUE_BUCKET}}/glue-jobs/ --recursive
