name: 'Terraform'

on:
  push:
    branches:
      - main
    paths:
      - devops/envs/dataart-2025/*
  
  pull_request:

permissions:
  contents: read
  id-token: write

jobs:
  terraform:
    uses: finddx/seq-treat-tbkb-github-workflows/.github/workflows/terraform.yml@main
    with:
      environment: dataart-2025
    secrets: inherit